name: Build and Test

on:
  push:
    branches: '**'

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        compiler: ["clang-10"]

    steps:
    - name: Checkout code including full history and submodules
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Install dependencies from APT repository
      run: |
        sudo apt-get update
        sudo apt-get install libcunit1-dev wget unzip

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Build all binaries
      run: |
        tools/ci/run_ci.sh --run-build --verbose
      env:
        CC:  ${{ matrix.compiler }}

    - name: Build, execute sanititzed unit tests
      run: |
        tools/ci/run_ci.sh --run-tests
      env:
        CC:  ${{ matrix.compiler }}

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    # You can test your matrix by printing the current Python version
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Display Python version
      run: |
          python -c "import sys; print(sys.version)"
          pytest -v
