name: Build and Test Special

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build_and_test_special:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        sanitizer: ["address", "leak", "thread", "undefined"]
        compiler: ["clang-10", "gcc-10"]

    steps:
    - name: Checkout code including full history and submodules
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Install dependencies from APT repository
      run: |
        sudo apt-get update
        sudo apt-get install libcunit1-dev wget unzip

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install dependencies
      run: |
          pip install -r tests/integration/requirements.txt

    - name: Build all binaries JSON
      run: |
        tools/ci/run_ci.sh --run-build --verbose --add-cmake-arg LWM2M_VERSION=1.0
      env:
        CC:  ${{ matrix.compiler }}

    - name: Execute JSON integration test
      run: |
          python -c "import sys; print(sys.version)"
          pytest -v tests/integration -k json_format

    - name: Build all binaries TLV
      run: |
        tools/ci/run_ci.sh --run-clean --run-build --verbose --add-cmake-arg CLIENT_TLV_ONLY=ON
      env:
        CC:  ${{ matrix.compiler }}

    - name: Execute TLV integration test
      run: |
          python -c "import sys; print(sys.version)"
          pytest -v tests/integration -k tlv_format

